"""add many to many relationship

Revision ID: 28b3883c3a7b
Revises: 57a35a4ca104
Create Date: 2024-04-17 12:54:40.360408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b3883c3a7b'
down_revision = '57a35a4ca104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_teams_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_teams_team_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_teams')
    # ### end Alembic commands ###
