"""update player model

Revision ID: 2bf8f7ec1ef1
Revises: aa1be228361f
Create Date: 2024-04-15 13:05:07.086403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf8f7ec1ef1'
down_revision = 'aa1be228361f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
