"""updated players table

Revision ID: 568a91c73278
Revises: 2bf8f7ec1ef1
Create Date: 2024-04-15 13:10:07.795170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568a91c73278'
down_revision = '2bf8f7ec1ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.String(), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
