"""create teams table

Revision ID: 7e948018c1ac
Revises: 
Create Date: 2024-04-15 12:37:12.540303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e948018c1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('regularR', sa.String(), nullable=False),
    sa.Column('playoffR', sa.String(), nullable=False),
    sa.Column('championships', sa.Integer(), nullable=False),
    sa.Column('titles', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('coach', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
