"""create stats tables

Revision ID: aa1be228361f
Revises: e9443aeaec98
Create Date: 2024-04-15 12:58:46.086165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1be228361f'
down_revision = 'e9443aeaec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('loses', sa.Integer(), nullable=False),
    sa.Column('cstanding', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('rebounds', sa.Float(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_teamstats_team_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=False),
    sa.Column('minpg', sa.Float(), nullable=False),
    sa.Column('rebpg', sa.Float(), nullable=False),
    sa.Column('ppg', sa.Float(), nullable=False),
    sa.Column('apg', sa.Float(), nullable=False),
    sa.Column('spg', sa.Float(), nullable=False),
    sa.Column('bpg', sa.Float(), nullable=False),
    sa.Column('tpg', sa.Float(), nullable=False),
    sa.Column('fgpercentage', sa.Float(), nullable=False),
    sa.Column('threepercentage', sa.Float(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_playerstats_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_playerstats_team_id_teams')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playerstats')
    op.drop_table('teamstats')
    # ### end Alembic commands ###
