"""delete foreign keys

Revision ID: ad535604b9e0
Revises: f3458492de29
Create Date: 2024-04-15 23:01:24.939483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad535604b9e0'
down_revision = 'f3458492de29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_team_id_teams', type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('playerstats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_playerstats_team_id_teams', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playerstats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_playerstats_team_id_teams', 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_players_team_id_teams', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###
