"""update players and teams table

Revision ID: f3458492de29
Revises: 568a91c73278
Create Date: 2024-04-15 22:23:46.277865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3458492de29'
down_revision = '568a91c73278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
